config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'admin'

  resources :teams do

    resources :organizations

    resources :people

    resources :activities

    resources :deals do
      get '/archive' => 'deals#archive', as: 'archive'
      get '/unarchive' => 'deals#unarchive', as: 'unarchive'
      get '/status' => 'deals#status', as: 'status'
    end

  end

  resources :visibilities
  get '/contacts/gmail', as: :contacts_push
  get '/teams/:team_id/contacts_callback' => 'people#contacts_callback', as: :contacts_callback
  get '/teams/:team_id/search' => 'teams#search', as: :search_team
  get '/teams/:team_id/export_deals' => 'teams#export_deals', as: :export_deals
  get '/teams/:team_id/export_people' => 'teams#export_people', as: :export_people
  get '/teams/:team_id/export_organizations' => 'teams#export_organizations', as: :export_organizations
  get '/teams/:team_id/export_activities' => 'teams#export_activities', as: :export_activities
  get '/teams/:team_id/export' => 'teams#export', as: :export_team
  get '/teams/:team_id/settings' => 'teams#settings', as: :settings_team

  get '/teams/:team_id/stats' => 'teams#stats', as: :stats_team
  get '/teams/:team_id/eagleview' => 'teams#eagleview', as: :eagleview_team
  get '/teams/:team_id/invite' => 'teams#invite', as: :invite_team
  get '/teams/:team_id/stages' => 'teams#stages', as: :stages_team
  get '/teams/:team_id/remove' => 'teams#remove', as: :remove_team
  post '/teams/:team_id/add_member' => 'teams#add_member', as: :add_member_team
  post '/teams/:team_id/upgrade' => 'teams#upgrade', as: :upgrade_team
  post '/teams/:team_id/card_edit' => 'teams#card_edit', as: :card_edit_team
  get '/teams/:team_id/change_card' => 'teams#change_card', as: :change_card_team
  get '/teams/:team_id/payment' => 'teams#payment', as: :payment_team
  post 'teams/:team_id/payment' => 'teams#payment', as: :post_payment_team
  devise_for :users, :controllers => { :registrations => "my_devise/registrations"}
  get '/tnc' => 'pages#tnc'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/refund_policy' => 'pages#refund_policy'

  root 'home#index'

end

app/models/person.rb
class Person < ApplicationRecord
	belongs_to :organization, optional:true
	validates_presence_of :name, :visibility_id, :user_id, :team_id
	belongs_to :team, optional:true
	has_many :deals
	has_many :emails
	has_many :phones
	has_many :activities
	accepts_nested_attributes_for :emails, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :phones, :reject_if => :all_blank, :allow_destroy => true


def self.to_csv
  CSV.generate do |csv|
    csv << ["Name", "Organization_name", "Primary_email", "Primary_phone", "Added_by"]
    all.each do |person|
      csv << [ person.name, (person.organization.name if person.organization), (person.emails.first.value if person.emails.count > 0 ),  (person.phones.first.number if person.phones.count > 0 ) , User.find(person.user_id).email ]
    end
  end
end



end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_team
  before_action :set_person, :except => [:index, :create, :new, :contacts_callback]
  before_action :authenticate_user!
  before_action :is_subscription_active
  before_action :is_this_a_team_i_belong_to_or_own?
  before_action :should_modal_be_open
  before_action :is_this_person_visible_to_me, :except => [:contacts_callback, :index, :create, :new]

  # GET /people
  # GET /people.json
  def index
    @people = @team.people.includes(:organization)
    @person = Person.new(:team_id => @team.id)
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

 def contacts_callback
 end

  # GET /people/new
  def new
    @person = Person.new(:team_id => @team.id)
    iwantmodal
    should_modal_be_open
    render :index
  end

  # GET /people/1/edit
  def edit
    iwantmodal
    should_modal_be_open
    render :index
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    @person.team = @team
    @person.user_id = current_user.id
    respond_to do |format|
      if @person.save
        format.html { redirect_to team_people_path(@team), notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        @people = @team.people.all
        iwantmodal
        should_modal_be_open
        format.html { render action: 'index' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to team_people_path(@team), notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        iwantmodal
        should_modal_be_open
        format.html { render action: 'index' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to team_people_url(@team) }
      format.json { head :no_content }
    end
  end

  private
      def set_team
      @team = Team.friendly.find(params[:team_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :organization_id, :visibility_id, emails_attributes: [:id, :value, :_destroy], phones_attributes: [:id, :number, :_destroy])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_email_fields.html.erb
<div class="col-md-offset-2 col-md-8 nested-fields">
	<%= f.input :value, label: "Email ID" do %>
		<div class="input-group">
			<%= f.input_field :value %>
			<span class="input-group-btn">
		  		<%=  link_to_remove_association 'x', f , class:"btn btn-danger" %>
		  	</span>
		</div>
	<% end %>
</div>

app/views/people/_form.html.erb
<% if !@person.blank? %>
  <div id="peopleModal" class="modal fade <%= 'open'.html_safe if @modal %>" aria-hidden="true">

    <div class="modal-dialog">

      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add a Person</h4>
        </div>

        <div class="modal-body">

          <%= simple_form_for([@person.team, @person], html: { class: "form-horizontal form-groups-bordered"}, defaults: { required: false, label_html: { class: 'control-label' }}) do |f| %>

            <%= f.error_notification %>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
              <%= f.input :name %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :organization_id, :collection => @team.organizations %>
              </div>
            </div>

            <%= f.simple_fields_for :phones do |phone| %>
              <%= render 'phone_fields', :f => phone %>
            <%end%>

            <div class="row">
                <div class="links">
                  <br/>
                  <%= link_to_add_association 'Add Phone Number', f, :phones, class: "btn btn-success col-md-8 col-md-offset-2" %>
                </div>
            </div>

            <br/>

            <%= f.simple_fields_for :emails do |email| %>
              <%= render 'people/email_fields', :f => email %>
            <%end%>

            <div class="row">
              <div class="links">
                <br/>
                <%= link_to_add_association 'Add Email ID', f, :emails, class: "btn btn-success col-md-8 col-md-offset-2" %>
              </div>
            </div>

            <br/>
            <br/>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :visibility_id, collection: Visibility.all,:include_blank => false %>
              </div>
            </div>

        </div>

        <div class="modal-footer">
          <div class="form-actions">
            <%= f.button :submit, class:"btn btn-primary", remote: true, method: :post %>
          </div>
        </div>

      <% end %>

      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<% end %>

app/views/people/_phone_fields.html.erb
<div class="col-md-offset-2 col-md-8 nested-fields">
	<%= f.input :number, label: "Phone Number" do %>
		<div class="input-group">
			<%= f.input_field :number %>
			<span class="input-group-btn">
	  			<%=  link_to_remove_association 'x', f , class:"btn btn-danger" %>
	  		</span>
	  	</div>
  	<% end %>
</div>

app/views/people/edit.html.erb
<h1>Editing <%= @person.name %>'s details</h1>

<% content_for :modal do %>
  <%= render 'people/form' %>
<% end %>
<%= link_to 'Back', team_people_path(@team), class: "btn btn-warning" %>

app/views/people/index.html.erb
<div class="panel panel-default">

  <div class="panel-heading clearfix">
    <i class="entypo-chart"></i>
      <h3 class="panel-title">People</h3>
  </div>

  <div class="panel-body">
    <div class="row">
    <div class="col-md-12">
    <%= link_to 'Add a Person +', new_team_person_path, class: 'btn btn-primary' %>
    <%# TODO Add Google Contacts
    =link_to (raw('<span>Add from Google Contacts</span>&nbsp;<i class="entypo-google-circles"></i>')), contacts_push_url,  class: "btn btn-gold" %>
    </div>
    </div>
    <br/>
    <div class="row">
    <div class="col-md-12">
<table class = "table table-condensed table-striped table-bordered table-hover no-margin">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Organization</th>
      <th>Added by</th>
      <th>Deals Associated</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if form_people.blank? %>
      <tr>
        <td colspan="6" class="text-center">You don't have any people in your contacts.</td>
      </tr>
    <% else %>
      <% form_people.each do |person| %>
        <tr>
          <td><strong><%= link_to person.name, edit_team_person_path(@team, person) %></strong></td>
           <td><%= person.emails.flat_map(&:value).join(", ") %></td>
          <td><%= person.organization.name if person.organization %></td>
          <td><%= User.find(person.user_id).email %></td>
           <td><%= Deal.where(:person_id => person.id).count %></td>
          <td><%= link_to 'Delete', team_person_path(@team, person), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>
<br>
<% content_for :modal do %>
  <%= render 'people/form' %>
<% end %>

app/views/people/new.html.erb
<h2>New person</h2>
<br/>
<div class="row">
	<div class="col-md-4">
		<a href="#" class="btn btn-lg btn-success"  data-toggle="modal" data-target="#peopleModal">Add A Person +</a>
	</div>
</div>
<br/>

<%= link_to 'Back', team_people_path %>
<% content_for :modal do %>
  <%= render 'people/form' %>
<% end %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Organization:</strong>
  <%= Organization.find(@person.organization_id).name if @person.organization %>
</p>
<p>
  <strong>Organization:</strong>
  <%= Organization.find(@person.organization_id).name if @person.organization %>
</p>
<p>
  <strong>Phones:</strong> <br/>
  <%@person.phones.each do |e| %>
  <%= e.number %> <br/>
  <%end %>
</p>
<p>
  <strong>Emails:</strong><br/>
  <%@person.emails.each do |e| %>
  <%= e.value %> <br/>
  <%end %>
</p>
<p>
  <strong>Added by:</strong>
  <%= User.find(@person.user_id).email %>
</p>

<p>
  <strong>Visibility:</strong>
  <%= Visibility.find(@person.visibility_id).name %>
</p>

<%= link_to 'Edit', edit_team_person_path(@team, @person) %>