config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'admin'

  resources :teams do

    resources :organizations

    resources :people

    resources :activities

    resources :deals do
      get '/archive' => 'deals#archive', as: 'archive'
      get '/unarchive' => 'deals#unarchive', as: 'unarchive'
      get '/status' => 'deals#status', as: 'status'
    end

  end

  resources :visibilities
  get '/contacts/gmail', as: :contacts_push
  get '/teams/:team_id/contacts_callback' => 'people#contacts_callback', as: :contacts_callback
  get '/teams/:team_id/search' => 'teams#search', as: :search_team
  get '/teams/:team_id/export_deals' => 'teams#export_deals', as: :export_deals
  get '/teams/:team_id/export_people' => 'teams#export_people', as: :export_people
  get '/teams/:team_id/export_organizations' => 'teams#export_organizations', as: :export_organizations
  get '/teams/:team_id/export_activities' => 'teams#export_activities', as: :export_activities
  get '/teams/:team_id/export' => 'teams#export', as: :export_team
  get '/teams/:team_id/settings' => 'teams#settings', as: :settings_team

  get '/teams/:team_id/stats' => 'teams#stats', as: :stats_team
  get '/teams/:team_id/eagleview' => 'teams#eagleview', as: :eagleview_team
  get '/teams/:team_id/invite' => 'teams#invite', as: :invite_team
  get '/teams/:team_id/stages' => 'teams#stages', as: :stages_team
  get '/teams/:team_id/remove' => 'teams#remove', as: :remove_team
  post '/teams/:team_id/add_member' => 'teams#add_member', as: :add_member_team
  post '/teams/:team_id/upgrade' => 'teams#upgrade', as: :upgrade_team
  post '/teams/:team_id/card_edit' => 'teams#card_edit', as: :card_edit_team
  get '/teams/:team_id/change_card' => 'teams#change_card', as: :change_card_team
  get '/teams/:team_id/payment' => 'teams#payment', as: :payment_team
  post 'teams/:team_id/payment' => 'teams#payment', as: :post_payment_team
  devise_for :users, :controllers => { :registrations => "my_devise/registrations"}
  get '/tnc' => 'pages#tnc'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/refund_policy' => 'pages#refund_policy'

  root 'home#index'

end

app/models/deal.rb
class Deal <  ApplicationRecord
  belongs_to :team
  belongs_to :stage
  belongs_to :person
  belongs_to :organization
  belongs_to :currency
  validates_presence_of :title, :value, :start_date, :stage_id, :visibility_id, :team_id, :user_id
  validates_datetime :start_date
  validates_datetime :close_date, :unless => 'close_date.blank?', :on_or_after => :start_date
  validates :value, numericality: { only_integer: true, :greater_than => -1, :less_than_or_equal_to => 10000000}
  validates :status, inclusion: { in: %w(Won Lost Pending) , message: "Not a valid status" }


def self.to_csv
  CSV.generate do |csv|
    csv << ["Title", "Contact_person", "Organization", "Email", "Phone", "Value", "Start_date", "Close_date", "Status", "Stage", "Deal Started By"]
    all.each do |deal|
      csv << [ deal.title, (deal.person.name if deal.person), (deal.organization.name if deal.organization), deal.email, deal.phone, deal.value, deal.start_date, deal.close_date, deal.status, deal.stage.name, User.find(deal.user_id).email]
    end
  end
end



end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_team
  before_action :set_deal, :except => [:index, :create, :new, :archive, :unarchive, :status]
  before_action :authenticate_user!
  before_action :is_subscription_active
  before_action :is_this_a_team_i_belong_to_or_own?
  before_action :should_modal_be_open
  before_action :is_this_deal_visible_to_me, :except => [:index, :create, :new, :archive, :unarchive, :status]
  require 'date'
  # GET /deals
  # GET /deals.json
  def index
    @deal = Deal.new(:team_id => @team.id)
    # Only visible deals should go into deals_by_month on the whole maybe we should only load visible deals
    #@deals_by_month = show_visible(@deals).sort_by(&:created_at).reverse.group_by { |deal| deal.created_at.strftime("%B '%g") }
    render action: 'all' if params[:view_mode] == "all"
  end

  def status
    @deal = @team.deals.find(params[:deal_id])
    @deal.status = params[:status]
    @deal.save
    redirect_to team_deals_path(@team)
  end

  def archive
    @deal = @team.deals.find(params[:deal_id])
    @deal.archived = true
    @deal.save
    redirect_to team_deals_path(@team)
  end

  def unarchive
    @deal = @team.deals.find(params[:deal_id])
    @deal.archived = false
    @deal.save
    redirect_to team_deals_path(@team)
  end

  def all
    @deals = @team.deals.where(archived: false)
    @deal = Deal.new(:team_id => @team.id)
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new(:team_id => @team.id)
  end

  # GET /deals/1/edit
  def edit
    iwantmodal
    should_modal_be_open
    render :index
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)
    @deal.team = @team
    @deal.user_id = current_user.id

    respond_to do |format|
      if @deal.save
        format.html { redirect_to team_deals_path(@team), notice: 'Deal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deal }
      else
        @deals = @team.deals
        iwantmodal
        should_modal_be_open
        format.html { render action: 'index' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update_attributes(deal_params)
        format.html { redirect_to team_deals_path(@team), notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
        format.js { render layout: false }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
        format.js { render layout: false }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to team_deals_url(@team) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_team
    @team = Team.friendly.find(params[:team_id])
  end

  def set_deal
    @deal = @team.deals.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def deal_params
    params.require(:deal).permit(:person_id, :organization_id, :title, :value, :close_date, :start_date, :status, :phone, :visibility_id, :archived, :email, :stage_id)
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_all_deals.html.erb
<div class="panel panel-primary">

  <div class="panel-heading">
    <div class="panel-title">
      Deals Dashboard
    </div>
  </div>

  <div class="panel-body deals-body min-htw">
    <div class="row">
      <div class="col-md-12 col-sm-12">
          <a href="#" class="btn btn-gold"  data-toggle="modal" data-target="#dealModal">
            Add A Deal +
          </a>
          <%= link_to "Switch to Active Deals View", team_deals_path, class: "btn btn-primary" %>
             <br/> <br/>
        </div>
        <br/>
    </div>

      <div class="scroll-body" id="<%= @team.friendly_id %>">

        <% @team.stages.all.each do |stage| %>

          <div id="<%= stage.id %>" class="scroll-column droppable">

            <h4 class="label-p stage-title"><p style="font-weight: 200; text-align:center; font-size:15px; padding-top:5px; padding-bottom:5px; color: #3b5998;font-family: "Noto Sans", sans-serif, "Helvetica Neue", Helvetica, Arial, sans-serif;"><%= stage.name %> (Total: <%= Currency.find(@team.currency_id).extension %> <%= number_with_delimiter(stage.deals.flat_map(&:value).reduce(:+)) || 0%> ) </p></h4>

            <% show_visible_deals(stage).each do |deal| %>

              <div id="<%= deal.id %>" class="tile-stats tile-<%= "#{dealcolor(deal.status, deal.archived)}" %> draggable notransition" data-stage-id="<%= deal.stage_id %>">
                <div class="num"><%= link_to deal.title, team_deal_path(@team, deal)%><%= link_to (raw('<i class="entypo-erase"></i>')), team_deal_path(@team, deal), method: :delete, data: { confirm: 'Are you sure?' }, class: 'pull-right' %></div> 
                <%= deal.status %>
                <%= link_to "#{time_ago_in_words(deal.created_at)} ago", edit_team_deal_path(@team, deal) %>
                <h5 class="number"><%= number_with_delimiter(deal.value) %> <%= Currency.find(@team.currency_id).extension %></h5>
                <h5 class="number"><%= deal.organization.name if deal.organization %></h5>
                <h5 class="number deal-btn-stack">
                <%= link_to (raw("<i class='entypo-folder'></i>Unarchive")), team_deal_unarchive_path(@team, deal), class: 'deal-btn'%>

                <% if deal.status == 'Won' %>

                <% elsif deal.status == 'Lost' %>
                 <% elsif deal.status == 'Pending' %>
                  <%= link_to (raw("<i class='entypo-thumbs-up'></i>Won")), team_deal_status_path(@team, deal, status: "Won"), class: 'deal-btn' %>
                  <%= link_to (raw("<i class='entypo-thumbs-down'></i>Lost")), team_deal_status_path(@team, deal, status: "Lost"), class: 'deal-btn' %>
                <% end %>
              </h5>
              </div>

            <% end %>

          </div>

        <% end %>

      </div>

  </div>

</div>
<% content_for :modal do %>
  <%= render 'deals/form' %>
<% end %>

app/views/deals/_deals.html.erb
<div class="panel panel-primary">

  <div class="panel-heading">
    <div class="panel-title">
      Deals Dashboard
    </a>
    </div>
  </div>

  <div class="panel-body deals-body min-htw">
    <div class="row">
      <div class="col-md-12 col-sm-12">
          <a href="#" class="btn btn-gold"  data-toggle="modal" data-target="#dealModal">
            Add A Deal +
          </a>
          <%= link_to "Switch to All Deals view", team_deals_path(view_mode: "all"), class: "btn btn-primary" %>
             <br/> <br/>
        </div>
        <br/>
    </div>

    <div class="scroll-body" id="<%= @team.friendly_id %>">

      <% @team.stages.all.each do |stage| %>

        <div id="<%= stage.id %>" class="scroll-column droppable">

          <h4 class="label-p stage-title"><p style="font-weight: 200; text-align:center; font-size:15px; padding-top:5px; padding-bottom:5px; color: #3b5998;font-family: "Noto Sans", sans-serif, "Helvetica Neue", Helvetica, Arial, sans-serif;"><%= stage.name %> (Total: <%= Currency.find(@team.currency_id).extension %> <%= number_with_delimiter(show_visible_unarchived_deals(stage).flat_map(&:value).reduce(:+)) || 0%> ) </p></h4>

          <% show_visible_unarchived_deals(stage).each do |deal| %>

            <div id="<%= deal.id %>" class="tile-stats tile-<%= "#{dealcolor(deal.status, deal.archived)}" %> draggable notransition" data-stage-id="<%= deal.stage_id %>">
              <div class="num"><%= link_to deal.title, team_deal_path(@team, deal)%><%= link_to (raw('<i class="entypo-erase"></i>')), team_deal_path(@team, deal), method: :delete, data: { confirm: 'Are you sure?' }, class: 'pull-right' %></div>
              <%= link_to "#{time_ago_in_words(deal.created_at)} ago", edit_team_deal_path(@team, deal) %>
              <h5 class="number"><%= number_with_delimiter(deal.value) %> <%= Currency.find(@team.currency_id).extension %></h5>
              <h5 class="number"><%= deal.organization.name if deal.organization %></h5>
              <h5 class="number deal-btn-stack">
                <%= link_to (raw("<i class='entypo-folder'></i>Archive")), team_deal_archive_path(@team, deal), class: 'deal-btn'%>

                <% if deal.status == 'Won' %>

                <% elsif deal.status == 'Lost' %>
                 <% elsif deal.status == 'Pending' %>
                  <%= link_to (raw("<i class='entypo-thumbs-up'></i>Won")), team_deal_status_path(@team, deal, status: "Won"), class: 'deal-btn' %>
                  <%= link_to (raw("<i class='entypo-thumbs-down'></i>Lost")), team_deal_status_path(@team, deal, status: "Lost"), class: 'deal-btn' %>
                <% end %>
              </h5>
            </div>

          <% end %>

        </div>

      <% end %>

    </div>

  </div>

</div>
<% content_for :modal do %>
  <%= render 'deals/form' %>
<% end %>

app/views/deals/_form.html.erb
<% if !@deal.blank? %>
  <div id="dealModal" class="modal fade <%= 'open'.html_safe if @modal %>" aria-hidden="true">

    <div class="modal-dialog">

      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Deal</h4>
        </div>

        <div class="modal-body">

          <%= simple_form_for([@deal.team, @deal], html: { class: "form-horizontal form-groups-bordered"}, defaults: { required: false, label_html: { class: 'control-label' }}) do |f| %>


            <%= f.error_notification %>


            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :person_id do %>
                <div class="input-group">
                  <%= f.input_field :person_id, :collection => @team.people, include_blank: false, class: 'add-side-btn' %>
                  <span class="input-group-btn">
                  <%= link_to "+", new_team_person_path, type: 'button', class: 'btn btn-success' %>
                  </span>
                </div>

                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :organization_id do %>
                <div class="input-group">
                  <%= f.input_field :organization_id, :collection => @team.organizations, include_blank: false, class: 'add-side-btn' %>
                <span class="input-group-btn">
                  <%= link_to "+", new_team_organization_path, type: 'button', class: 'btn btn-success' %>
                </span>
                </div>
                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :email %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :phone %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :title %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :value %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :start_date, :as => :datetime_picker%>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :close_date, :as => :datetime_picker %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :status, collection:['Pending', 'Won','Lost'], :include_blank => false %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :visibility_id, collection: Visibility.all,:include_blank => false %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :stage_id, :collection => @team.stages, :include_blank => false %>
              </div>
            </div>

        </div>

        <div class="modal-footer">
          <div class="form-actions">
            <%= f.button :submit, class:"btn btn-primary", remote: true, method: :post %>
          </div>
        </div>

      <% end %>

      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<% end %>

app/views/deals/all.html.erb
<h2>Dashboard</h2>
<div class="scrollholder">
 <%= render 'all_deals' %>
</div>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<% content_for :modal do %>
  <%= render 'deals/form' %>
<% end %>

<%= link_to 'Back', team_deals_path(@team), class: "btn btn-warning" %>

app/views/deals/index.html.erb
<h2>Dashboard</h2>
<p></p>
<br/>
<!--
<div class="dashboard_tips">
<p><span style= "color: white">Tip #1:</span> Drag and drop deals into different stages. Won Deals are <span style="color: green;">Green</span>, Lost Deals are <span style="color: red;">Red</span> and Pending Deals are <span style="color: orange;">Orange</span>.<br/>
<span style= "color: white">Tip #2:</span> You should archive deals that are no longer active. You can view them by clicking the "Archived" button.</p> 
</div>
<br/>-->
<div class="scrollholder">
 <%= render 'deals' %>
</div>

app/views/deals/new.html.erb
<h1>New deal</h1>

<% content_for :modal do %>
  <%= render 'deals/form' %>
<% end %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-info">
  <div class="panel-heading">
  <div class="panel-title">
    Details (Deal: <%= @deal.status %>)
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
    <div class="col-md-4">
      <h5><strong>Contact name:</strong>
      <%= @deal.person.name if @deal.person%></h5>

      <h5><strong>Company:</strong>
      <%= @deal.organization.name if @deal.organization%></h5>

      <h5><strong>Title:</strong>
      <%= @deal.title %></h5>

      <h5><strong>Stage:</strong>
      <%= @deal.stage.name %></h5>

    </div>
    <div class="col-md-4">

      <h5><strong>Value:</strong>
      <%= @deal.value %></h5>

      <h5><strong>Start date:</strong>
      <%= @deal.start_date %></h5>

      <h5><strong>Close date:</strong>
      <%= @deal.close_date %></h5>
    </div>

    <div class="col-md-4">

      <h5><strong>Visibility:</strong>
      <%= Visibility.find(@deal.visibility_id).name %></h5>

      <h5><strong>Phone:</strong>
      <%= @deal.phone %></h5>

      <h5><strong>Email:</strong>
      <%= @deal.email %></h5>

      <h5><strong>Member who started this deal:</strong>
      <%= User.find(@deal.user_id).email %></h5>

    </div>
  </div>
      <br/>

    <br/>

    <div class="row">
      <div class="col-md-4">
        <%= link_to 'Edit', edit_team_deal_path(@team, @deal), class: 'btn btn-info' %>
        <%= link_to 'Back', team_deals_path, class: 'btn btn-warning' %>
        <%= link_to 'Delete', team_deal_path(@team, @deal), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/deals/timeline.html.erb
<%= render 'actionbar' %>
<div class="scroll-body" id="<%= @team.friendly_id %>">
    <% @deals_by_month.each do |monthname, deals| %>
        <div class="scroll-column droppable">
            <h4 class="label-p stage-title"><strong><%= monthname %></strong></h4>
            <% deals.each do |deal| %>
            <div id="<%= deal.id %>" class="panel panel-default scroll-item timed draggable" data-stage-id="<%= deal.stage_id %>">
              <div class="panel-sub-heading">
              <% if deal.status=='Won' %>
              <p class="label label-success pull-left lab">WON</p>
              <%elsif  deal.status=='Lost' %>
               <p class="label label-danger pull-left lab">LOST</p>
              <%else%>
              <p class="label label-warning pull-left lab">PENDING</p>
              <%end%>

          <a href="#"><%= time_ago_in_words deal.created_at %> ago</a>
        </div>
            <div class="daily-stats">

                <h4 class="d-title"><%= link_to deal.title, team_deal_path(@team, deal)%></h4>
                <h4 class="number"><%= deal.value %> <%= deal.currency.extension %></h4>
                </div>

            </div>
            <% end %>

        </div>
    <% end %>
</div>

app/views/deals/update.js.erb
(function($) {
  $.QueryString = (function(a) {
    if (a == "") return {};
    var b = {};
    for (var i = 0; i < a.length; ++i)
    {
      var p=a[i].split('=');
      if (p.length != 2) continue;
      b[p[0]] = decodeURIComponent(p[1].replace(/\+/g, " "));
    }
    return b;
  })(window.location.search.substr(1).split('&'))

  if($.QueryString["view_mode"] == 'all') $('.scrollholder').html("<%= j render 'all_deals' %>")
  else $('.scrollholder').html("<%= j render 'deals' %>");
})(jQuery);