config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'admin'

  resources :teams do

    resources :organizations

    resources :people

    resources :activities

    resources :deals do
      get '/archive' => 'deals#archive', as: 'archive'
      get '/unarchive' => 'deals#unarchive', as: 'unarchive'
      get '/status' => 'deals#status', as: 'status'
    end

  end

  resources :visibilities
  get '/contacts/gmail', as: :contacts_push
  get '/teams/:team_id/contacts_callback' => 'people#contacts_callback', as: :contacts_callback
  get '/teams/:team_id/search' => 'teams#search', as: :search_team
  get '/teams/:team_id/export_deals' => 'teams#export_deals', as: :export_deals
  get '/teams/:team_id/export_people' => 'teams#export_people', as: :export_people
  get '/teams/:team_id/export_organizations' => 'teams#export_organizations', as: :export_organizations
  get '/teams/:team_id/export_activities' => 'teams#export_activities', as: :export_activities
  get '/teams/:team_id/export' => 'teams#export', as: :export_team
  get '/teams/:team_id/settings' => 'teams#settings', as: :settings_team

  get '/teams/:team_id/stats' => 'teams#stats', as: :stats_team
  get '/teams/:team_id/eagleview' => 'teams#eagleview', as: :eagleview_team
  get '/teams/:team_id/invite' => 'teams#invite', as: :invite_team
  get '/teams/:team_id/stages' => 'teams#stages', as: :stages_team
  get '/teams/:team_id/remove' => 'teams#remove', as: :remove_team
  post '/teams/:team_id/add_member' => 'teams#add_member', as: :add_member_team
  post '/teams/:team_id/upgrade' => 'teams#upgrade', as: :upgrade_team
  post '/teams/:team_id/card_edit' => 'teams#card_edit', as: :card_edit_team
  get '/teams/:team_id/change_card' => 'teams#change_card', as: :change_card_team
  get '/teams/:team_id/payment' => 'teams#payment', as: :payment_team
  post 'teams/:team_id/payment' => 'teams#payment', as: :post_payment_team
  devise_for :users, :controllers => { :registrations => "my_devise/registrations"}
  get '/tnc' => 'pages#tnc'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/refund_policy' => 'pages#refund_policy'

  root 'home#index'

end

app/models/stage.rb
class Stage < ApplicationRecord
	belongs_to :team, optional:true
	has_many :deals
	validates_presence_of  :name
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController

  before_action :set_stage, only: [:show, :edit, :update, :destroy]
  # GET /stages
  # GET /stages.json
  def index
    @stages = Stage.all
  end

  # GET /stages/1
  # GET /stages/1.json
  def show
  end

  # GET /stages/new
  def new
    @stage = Stage.new
  end

  # GET /stages/1/edit
  def edit
  end

  # POST /stages
  # POST /stages.json
  def create
    @stage = Stage.new(stage_params)

    respond_to do |format|
      if @stage.save
        format.html { redirect_to @stage, notice: 'Stage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stage }
      else
        format.html { render action: 'new' }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stages/1
  # PATCH/PUT /stages/1.json
  def update
    respond_to do |format|
      if @stage.update(stage_params)
        format.html { redirect_to @stage, notice: 'Stage was successfully updated.' }
        format.json { head :no_content }
      else
        iwantmodal
        should_modal_be_open
        format.html { render action: 'index' }
        format.json { render json: @stage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stages/1
  # DELETE /stages/1.json
  def destroy
    @stage.destroy
    respond_to do |format|
      format.html { redirect_to stages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stage
      @stage = Stage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
      params.require(:stage).permit(:name, :team_id)
    end
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= simple_form_for(@stage) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :team_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing stage</h1>

<%= render 'form' %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<h1>Listing stages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stages.each do |stage| %>
      <tr>
        <td><%= stage.name %></td>
        <td><%= stage.team_id %></td>
        <td><%= link_to 'Show', stage %></td>
        <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
        <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New stage</h1>

<%= render 'form' %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stage.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @stage.team_id %>
</p>

<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>