config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'admin'

  resources :teams do

    resources :organizations

    resources :people

    resources :activities

    resources :deals do
      get '/archive' => 'deals#archive', as: 'archive'
      get '/unarchive' => 'deals#unarchive', as: 'unarchive'
      get '/status' => 'deals#status', as: 'status'
    end

  end

  resources :visibilities
  get '/contacts/gmail', as: :contacts_push
  get '/teams/:team_id/contacts_callback' => 'people#contacts_callback', as: :contacts_callback
  get '/teams/:team_id/search' => 'teams#search', as: :search_team
  get '/teams/:team_id/export_deals' => 'teams#export_deals', as: :export_deals
  get '/teams/:team_id/export_people' => 'teams#export_people', as: :export_people
  get '/teams/:team_id/export_organizations' => 'teams#export_organizations', as: :export_organizations
  get '/teams/:team_id/export_activities' => 'teams#export_activities', as: :export_activities
  get '/teams/:team_id/export' => 'teams#export', as: :export_team
  get '/teams/:team_id/settings' => 'teams#settings', as: :settings_team

  get '/teams/:team_id/stats' => 'teams#stats', as: :stats_team
  get '/teams/:team_id/eagleview' => 'teams#eagleview', as: :eagleview_team
  get '/teams/:team_id/invite' => 'teams#invite', as: :invite_team
  get '/teams/:team_id/stages' => 'teams#stages', as: :stages_team
  get '/teams/:team_id/remove' => 'teams#remove', as: :remove_team
  post '/teams/:team_id/add_member' => 'teams#add_member', as: :add_member_team
  post '/teams/:team_id/upgrade' => 'teams#upgrade', as: :upgrade_team
  post '/teams/:team_id/card_edit' => 'teams#card_edit', as: :card_edit_team
  get '/teams/:team_id/change_card' => 'teams#change_card', as: :change_card_team
  get '/teams/:team_id/payment' => 'teams#payment', as: :payment_team
  post 'teams/:team_id/payment' => 'teams#payment', as: :post_payment_team
  devise_for :users, :controllers => { :registrations => "my_devise/registrations"}
  get '/tnc' => 'pages#tnc'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/refund_policy' => 'pages#refund_policy'

  root 'home#index'

end

app/models/activity.rb
class Activity < ApplicationRecord
	belongs_to :team
	belongs_to :deal
	belongs_to :type
    belongs_to :person
	validates_presence_of :name, :team_id, :type_id, :date, :user_id
	validates_datetime :date
	validates :length, numericality: { only_integer: true, :greater_than => -1 }


  def self.to_csv
  CSV.generate do |csv|
    csv << ["Name", "Deal_name", "Person_name", "Organization_name", "Type", "Note", "Date", "Time(in hours)", "Reponsibility", "Status"]
    all.each do |activity|
      csv << [ activity.name, (activity.person.name if activity.person), (activity.person.organization if activity.person), (activity.type.name if activity.type),  activity.note, activity.date, activity.length, User.find(activity.user_id).email, activity.done]
  end
end
end


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_team
  before_action :set_activity, except: [:index, :create, :new]
  before_action :authenticate_user!
   before_action :is_subscription_active
  before_action :is_this_a_team_i_belong_to_or_own?
  before_action :should_modal_be_open
  before_action :is_this_activity_visible_to_me, :except => [:index, :create, :new]


  # GET /activities
  # GET /activities.json
  def index
    @activities = @team.activities
    @activity = Activity.new(team_id: @team.id)
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new(team_id: @team.id)
    iwantmodal
    should_modal_be_open
    render :index
  end

  # GET /activities/1/edit
  def edit
    iwantmodal
    should_modal_be_open
    render :index
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.team = @team

    respond_to do |format|
      if @activity.save
        format.html { redirect_to team_activities_path(@team), notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        @activities = @team.activities
        iwantmodal
        should_modal_be_open
        format.html { render action: 'index' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to team_activities_path(@team), notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        iwantmodal
        should_modal_be_open
        format.html { render action: 'index' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to team_activities_path(@team) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.friendly.find(params[:team_id])
    end

    def set_activity
      @activity = @team.activities.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :deal_id, :team_id, :person_id, :organization_id, :type_id, :note, :date, :time, :length, :user_id, :done)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<% if !@activity.blank? %>
  <div id="activityModal" class="modal fade <%= 'open'.html_safe if @modal %>">
    
    <div class="modal-dialog">
      
      <div class="modal-content">
        
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Activity</h4>
        </div>

        <div class="modal-body">

          <%= simple_form_for([@activity.team, @activity], html: { class: "form-horizontal form-groups-bordered"}, defaults: { required: false, label_html: { class: 'control-label' }}) do |f| %>
          
            <%= f.error_notification %>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :name %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :deal_id, :collection => form_deals,  label_method: lambda { |obj| t("#{obj.title}") } %>
              </div>
            </div>

             <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :person_id do %>
                <div class="input-group">
                  <%= f.input_field :person_id, :collection => @team.people, class: 'add-side-btn' %>
                  <span class="input-group-btn">
                  <%= link_to "+", new_team_person_path, type: 'button', class: 'btn btn-success' %>
                  </span>
                </div>

                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :organization_id do %>
                <div class="input-group">
                  <%= f.input_field :organization_id, :collection => @team.organizations, class: 'add-side-btn' %>
                <span class="input-group-btn">
                  <%= link_to "+", new_team_organization_path, type: 'button', class: 'btn btn-success' %>
                </span>
                </div>
                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :type_id, :include_blank => false , :collection => Type.all,  label_method: lambda { |obj| t("#{obj.name}") } %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :note, as: :text %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :date,:as => :datetime_picker, input_html: {class: "activity_date"} %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :length, label: "Amount of time (in hours)" %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :user_id, :collection => all_users(@team), :include_blank => false, label: 'User Responsible', label_method: lambda { |obj| obj.email } %>
              </div>
            </div>

            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.input :done, as: :boolean %>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <div class="form-actions">
            <%= f.button :submit, class:"btn btn-primary", remote: true, method: :post %>
          </div>
        </div>
      <% end %>
        
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>
<% content_for :modal do %>
  <%= render 'activities/form' %>
<% end %>
<%= link_to 'Back',  team_activities_path(@team), class: "btn btn-warning" %>

app/views/activities/index.html.erb
<h2>Activities</h2>
<p>Add, edit and delete activities here.</p>
<br/><div class="panel panel-default">
  <div class="panel-heading clearfix">
              <i class="icon-bar-chart"></i>
              <h3 class="panel-title">Activities</h3>
            </div>
            <div class="panel-body">
              <%= link_to 'Add an Activity +', new_team_activity_path, class: 'btn btn-primary' %>
              <br/>
              <br/>
<!-- MODAL THIS -->

<table class="table table-condensed table-striped table-bordered table-hover no-margin">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Responsible</th>
      <th>With</th>
      <th>Note</th>
      <th>Date</th>
      <th>Done</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @team.activities.blank? %>
      <tr>
        <td colspan="8" class="text-center">You don't have any activities.</td>
      </tr>
    <% else %>
      <% @team.activities.includes(:type).each do |activity| %>
      <%if activity.deal_id %>
      <% if (Deal.find(activity.deal_id).visibility_id == 1) || (Deal.find(activity.deal_id).visibility_id == 2 && Deal.find(activity.deal_id).user_id == current_user.id)%>
        <tr>
          <td><strong><%= link_to activity.name, edit_team_activity_path(@team, activity) %></strong></td>
          <td><%= activity.type.name.capitalize %></td>
          <td><%= User.find(activity.user_id).email  %></td>
          <td><%= activity.person.name if activity.person%></td>
          <td><%= activity.note %></td>
          <td><%= activity.date.to_formatted_s(:long) %></td>
          <td><%= activity.done %></td>
          <td><%= link_to 'Delete', team_activity_path(@team, activity), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <%end %>
        <% else %>
        <tr>
          <td><%= link_to activity.name, edit_team_activity_path(@team, activity) %></td>
          <td><%= activity.type.name %></td>
          <td><%= User.find(activity.user_id).email  %></td>
          <td><%= activity.person.name if activity.person%></td>
          <td><%= activity.note %></td>
          <td><%= activity.date %></td>
          <td><%= activity.done %></td>
          <td><%= link_to 'Delete', team_activity_path(@team, activity), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <%end %>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>
<% content_for :modal do %>
  <%= render 'activities/form' %>
<% end %>

app/views/activities/new.html.erb
<h1>New activity</h1>
<% content_for :modal do %>
  <%= render 'activities/form' %>
<% end %>

<%# link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Deal:</strong>
  <%= @activity.deal_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @activity.team_id %>
</p>

<p>
  <strong>Contact:</strong>
  <%= Person.find(@activity.person_id).name if @activity.person_id%>
</p>

<p>
  <strong>Organization:</strong>
  <%= Organization.find(@activity.organization_id).name if @activity.organization_id%>
</p>

<p>
  <strong>Type:</strong>
  <%= @activity.type_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @activity.note %>
</p>

<p>
  <strong>Date:</strong>
  <%= @activity.date %>
</p>

<p>
  <strong>Length:</strong>
  <%= @activity.length %>
</p>

<p>
  <strong>User:</strong>
  <%= @activity.user_id %>
</p>

<p>
  <strong>Done:</strong>
  <%= @activity.done %>
</p>

<%= link_to 'Edit', edit_team_activity_path(@team, @activity) %>